name: Add release

on:
  release:
    types: [released]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}

jobs:
  release:
    name: Build binary and attach it to the release
    runs-on: ubuntu-20.04
    steps:
      - name: Git / Checkout
        uses: actions/checkout@v2

      - name: Go / Setup
        uses: actions/setup-go@v3
        with:
          go-version: '=1.19.3'

      - name: Go / Build binary
        shell: bash
        run: |
          go build

      - name: Release | Add binary to the release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            grafana-sidecar-users-yaml

